# Generated by Django 4.0.1 on 2022-03-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=20)),
                ('sensor', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=20)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
